apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationRestore
metadata:
  name: "{{ pxb_restore_name }}"
  namespace: "{{ pxb_restore_namespace }}"
spec:
  backupName: "{{ pxb_restore_backup_name }}"
  backupLocation: "{{ pxb_restore_backup_location }}"
  namespaceMapping: null
  replacePolicy: Delete
