apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: "{{ pxb_recovery_configuration_app_backup_schedule_name }}"
  namespace: "{{ pxb_recovery_configuration_namespace }}"
spec:
  backupType: ""
  parallelBackup: false
  reclaimPolicy: Retain
  schedulePolicyName: "{{ pxb_recovery_configuration_schedule_policy_name }}"
  suspend: false
  template:
    spec:
      advancedResourceLabelSelector: ""
      backupLocation: "{{ pxb_recovery_configuration_backup_location_name }}"
      backupObjectType: All
      backupType: ""
{% if pxb_recovery_configuration_csi_snapshot_class_map | default({}) %}
      csiSnapshotClassMap:
{% for driver, class_name in (pxb_recovery_configuration_csi_snapshot_class_map | default({})).items() %}
        {{ driver }}: {{ class_name }}
{% endfor %}
{% else %}
      csiSnapshotClassMap: {}
{% endif %}
      directKDMP: false
      excludeResourceTypes: null
      includeResources: null
      keepCrStatus: false
      missingNamespaces: null
      namespaceSelector: ""
      namespaces:
        - "{{ pxb_recovery_configuration_app_namespace }}"
      options:
        portworx.io/cloudsnap-incremental-count: "2"
      platformCredential: ""
      postExecRule: ""
      preExecRule: ""
      rancherProjects: null
      reclaimPolicy: Delete
      resourceTypes: null
      selectors: null
      skipAutoExecRules: false
      skipServiceUpdate: false
      volumeResourceOnlyPolicy: ""