apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: "{{ pxb_recovery_configuration_backup_location_name }}"
  namespace: "{{ pxb_recovery_configuration_namespace }}"
location:
  type: azure
  path: "{{ pxb_recovery_configuration_backup_location_azure.path }}"
  sync: true
  azureConfig:
    storageAccountName: "{{ pxb_recovery_configuration_backup_location_azure.storage_account_name }}"
    storageAccountKey: "{{ pxb_recovery_configuration_backup_location_azure.storage_account_key }}"
